enum_discrim_align_threshold = 60
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
# normalize_comments = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
style_edition = "2024"
wrap_comments = true
